seed: 0
trainer:
  type: models.trainers.MultiTrainer
  optim:
    num_iters: 30000
    use_grad_scaler: false
    cache_buffer_freq: -1
  render:
    near_plane: 0.1
    far_plane: 10000000000.0
    antialiased: false
    packed: false
    absgrad: true
    sparse_grad: false
    batch_size: 1
  losses:
    rgb:
      w: 0.8
    ssim:
      w: 0.2
    mask:
      w: 0.05
      opacity_loss_type: bce
    depth:
      w: 0.01
      inverse_depth: false
      normalize: false
      loss_type: l1
    affine:
      w: 1.0e-05
  res_schedule:
    double_steps: 250
    downscale_times: 2
  gaussian_optim_general_cfg:
    xyz:
      lr: 0.00016
      lr_final: 1.6e-06
      scale_factor: scene_radius
    sh_dc:
      lr: 0.0025
    sh_rest:
      lr: 0.000125
    opacity:
      lr: 0.05
    scaling:
      lr: 0.005
    rotation:
      lr: 0.001
  gaussian_ctrl_general_cfg:
    warmup_steps: 500
    reset_alpha_interval: 3000
    refine_interval: 100
    sh_degree_interval: 1000
    n_split_samples: 2
    reset_alpha_value: 0.01
    densify_grad_thresh: 0.0005
    densify_size_thresh: 0.003
    cull_alpha_thresh: 0.005
    cull_scale_thresh: 0.5
    cull_screen_size: 0.15
    split_screen_size: 0.05
    stop_screen_size_at: 4000
    stop_split_at: 15000
    sh_degree: 3
model:
  Background:
    type: models.gaussians.VanillaGaussians
    init:
      from_lidar:
        num_samples: 800000
        return_color: true
      near_randoms: 100000
      far_randoms: 100000
    reg:
      sharp_shape_reg:
        w: 1.0
        step_interval: 10
        max_gauss_ratio: 10.0
  RigidNodes:
    type: models.nodes.RigidNodes
    init:
      instance_max_pts: 5000
      only_moving: true
      traj_length_thres: 1.0
    ctrl:
      cull_scale_thresh: 0.1
      stop_screen_size_at: 30000
      stop_split_at: 20000
      cull_out_of_bound: true
    reg:
      sharp_shape_reg:
        w: 1.0
        step_interval: 10
        max_gauss_ratio: 10.0
      temporal_smooth_reg:
        trans:
          w: 0.01
          smooth_range: 5
    optim:
      ins_rotation:
        lr: 1.0e-05
        lr_final: 5.0e-06
      ins_translation:
        lr: 0.0005
        lr_final: 0.0001
  DeformableNodes:
    type: models.nodes.DeformableNodes
    init:
      instance_max_pts: 5000
      only_moving: true
      traj_length_thres: 0.5
    networks:
      D: 8
      W: 256
      embed_dim: 16
      x_multires: 10
      t_multires: 10
      deform_quat: true
      deform_scale: false
    ctrl:
      reset_alpha_value: 0.1
      cull_scale_thresh: 0.1
      stop_screen_size_at: 30000
      stop_split_at: 20000
      sh_degree: 3
      cull_out_of_bound: false
      use_deformgs_for_nonrigid: true
      use_deformgs_after: 3000
      stop_optimizing_canonical_xyz: true
    reg:
      sharp_shape_reg:
        w: 1.0
        step_interval: 10
        max_gauss_ratio: 10.0
      out_of_bound_loss:
        w: 1.0
        stop_after: 30000
      temporal_smooth_reg:
        trans:
          w: 0.01
          smooth_range: 5
    optim:
      xyz:
        lr: 0.00016
        lr_final: 1.6e-06
        scale_factor: 2.0
      embedding:
        lr: 0.001
        lr_final: 0.0001
      deform_network:
        lr: 0.0016
        lr_final: 0.00016
        scale_factor: 5.0
      ins_rotation:
        lr: 1.0e-05
        lr_final: 5.0e-06
      ins_translation:
        lr: 0.0005
        lr_final: 0.0001
  SMPLNodes:
    type: models.nodes.SMPLNodes
    init:
      only_moving: true
      traj_length_thres: 0.5
    reg:
      sharp_shape_reg:
        w: 1.0
        step_interval: 10
        max_gauss_ratio: 10.0
      temporal_smooth_reg:
        trans:
          w: 0.01
          smooth_range: 5
      knn_reg:
        lambda_std_q: 0.001
        lambda_std_s: 0.001
        lambda_std_o: 0.001
        lambda_std_shs_dc: 0.001
        lambda_std_shs_rest: 0.001
      max_s_square_reg:
        w: 0.05
      x_offset:
        w: 0.2
      voxel_deformer_reg:
        lambda_std_w: 0.6
        lambda_std_w_rest: 0.5
        lambda_w_norm: 0.6
        lambda_w_rest_norm: 0.3
    optim:
      xyz:
        lr: 0.00016
        lr_final: 1.6e-06
        scale_factor: 3.0
      rotation:
        lr: 0.005
      sh_dc:
        lr: 0.005
      sh_rest:
        lr: 0.00025
      ins_rotation:
        lr: 1.0e-05
        lr_final: 5.0e-06
      ins_translation:
        lr: 0.0005
        lr_final: 0.0001
      smpl_rotation:
        lr: 5.0e-05
        lr_final: 1.0e-05
      w_dc_vox:
        lr: 0.0001
        lr_final: 1.0e-05
        opt_after: 10000
    ctrl:
      sh_degree: 1
      opacity_init_value: 0.99
      ball_gaussians: false
      constrain_xyz_offset: false
      knn_update_interval: 100
      knn_neighbors: 3
      use_voxel_deformer: true
      freeze_x: false
      freeze_o: false
      freeze_q: false
      freeze_s: false
      freeze_shs_dc: false
      freeze_shs_rest: false
  Sky:
    type: models.modules.EnvLight
    params:
      resolution: 1024
    optim:
      all:
        lr: 0.01
  Affine:
    type: models.modules.AffineTransform
    params:
      embedding_dim: 4
      base_mlp_layer_width: 64
      pixel_affine: false
    optim:
      all:
        lr: 1.0e-05
        weight_decay: 1.0e-06
  CamPose:
    type: models.modules.CameraOptModule
    optim:
      all:
        lr: 1.0e-05
        weight_decay: 1.0e-06
render:
  fps: 10
  render_full: true
  render_test: true
  render_novel:
    traj_types:
    - s_curve
    fps: 24
  vis_lidar: true
  vis_sky: true
  vis_error: true
logging:
  vis_freq: 2000
  print_freq: 500
  saveckpt_freq: 40000
  save_seperate_video: true
data:
  data_root: data/waymo/processed/training
  dataset: waymo
  scene_idx: 16
  start_timestep: 0
  end_timestep: 150
  preload_device: cuda
  pixel_source:
    type: datasets.waymo.waymo_sourceloader.WaymoPixelSource
    cameras:
    - 0
    - 1
    - 2
    downscale_when_loading:
    - 2
    - 2
    - 2
    downscale: 1
    undistort: true
    test_image_stride: 0
    load_sky_mask: true
    load_dynamic_mask: true
    load_objects: true
    load_smpl: true
    sampler:
      buffer_downscale: 8
      buffer_ratio: 0.5
      start_enhance_weight: 3
  lidar_source:
    type: datasets.waymo.waymo_sourceloader.WaymoLiDARSource
    load_lidar: true
    only_use_top_lidar: false
    truncated_max_range: 80
    truncated_min_range: -2
    lidar_downsample_factor: 4
    lidar_percentile: 0.02
\: null
--output_root: null
$output_root: null
--project: null
waymo: null
--run_name: null
test_016_3cams_2: null
log_dir: ./work_dirs/drivestudio/omnire
